export const prodF = [
    {
        "id": 1000,
        "title": "Small Pizza Deal",
        "description": "Any Flavor From Local Love Or Over the Sea Flavor Category & 1 Soft Drink",
        "thumbnail": "/Images/pizza-1.png",
        "price": 650,
        "quantity": 0,
    },
    {
        "id": 2000,
        "title": "Regular Pizza Deal",
        "description": "1 Regular Pizza and 2 Regular Drinks.",
        "thumbnail": "/Images/pizza-2.png",
        "price": 1350,
        "quantity": 0,
    },
    {
        "id": 3000,
        "title": "Large Pizza Deal",
        "description": "Any Flavor From Local Love Or Over the Sea Flavor Category & 1 Liter Drink",
        "thumbnail": "/Images/pizza-3.png",
        "price": 1790,
        "quantity": 0,
    },
    {
        "id": 4000,
        "title": "Small Pizza Deal",
        "description": "Any Flavor From Local Love Or Over the Sea Flavor Category & 1 Soft Drink",
        "thumbnail": "/Images/pizza-4.png",
        "price": 650,
        "quantity": 0,
    },
    {
        "id": 5000,
        "title": "Regular Pizza Deal",
        "description": "1 Regular Pizza and 2 Regular Drinks.",
        "thumbnail": "/Images/pizza-5.png",
        "price": 1350,
        "quantity": 0,
    },
    {
        "id": 6000,
        "title": "Large Pizza Deal",
        "description": "Any Flavor From Local Love Or Over the Sea Flavor Category & 1 Liter Drink",
        "thumbnail": "/Images/pizza-6.png",
        "price": 1790,
        "quantity": 0,
    },
]