export const prodD = [
    {
        "id": 100,
        "title": "Chicken Pepperoni Pizza",
        "description": "Chicken Pepperoni, Pizza Sauce and Cheese",
        "thumbnail": "/Images/sooper-1.png",
        "price": 590,
        "quantity": 0,
    },
    {
        "id": 200,
        "title": "Cheese Lover Pizza",
        "description": "Yummiest Blend of Cheese and Pizza Sauce",
        "thumbnail": "/Images/sooper-2.png",
        "price": 590,
        "quantity": 0,
    },
    {
        "id": 300,
        "title": "Sausage Pizza",
        "description": "Chicken Sausages, Pizza Sauce and Cheese",
        "thumbnail": "/Images/sooper-3.png",
        "price": 590,
        "quantity": 0,
    },
    {
        "id": 400,
        "title": "Chicken Mushroom",
        "description": "Tender Chunks of Marinated Grilled Chicken Tikka, Lots of Mushrooms, Onion and Tomato Sauce",
        "thumbnail": "/Images/sooper-4.png",
        "price": 590,
        "quantity": 0,
    },
    {
        "id": 500,
        "title": "Black Pepper Tikka",
        "description": "A Blend of Marinated Black Pepper Chicken, Onion & Bell Pepper",
        "thumbnail": "/Images/sooper-5.png",
        "price": 500,
        "quantity": 0,
    },
    {
        "id": 600,
        "title": "Chicken Supreme",
        "description": "A Combination Of 3 Flavors of Chicken, Black Olives, Mushrooms Bell Pepper and Onion with Tomato Sauce.",
        "thumbnail": "/Images/sooper-6.png",
        "price": 590,
        "quantity": 0,
    },
    {
        "id": 7,
        "title": "Euro",
        "description": "Delight Combination of Specially Marinated Smoked Chicken Bell Pepper, Mushrooms with Tomato Sauce",
        "thumbnail": "/Images/sooper-7.png",
        "price": 690,
        "quantity": 0,
    },
]