export const prodC = [
    {
        "id": 10,
        "title": "Chicken Tikka",
        "description": "Tender Chunks of Marinated Grilled Chicken with Savory Onion",
        "thumbnail": "/Images/sLocal-1.png",
        "price": 590,
        "quantity": 0,
    },
    {
        "id": 20,
        "title": "Chicken Fajita",
        "description": "An Authentic Taste of Fajita Marinated Chicken Onion and Bell Peppers.",
        "thumbnail": "/Images/sLocal-2.png",
        "price": 590,
        "quantity": 0,
    },
    {
        "id": 30,
        "title": "Chicken Lover",
        "description": "Extreme Quantity of Chicken and Onion with Rich Mozzarella Cheese",
        "thumbnail": "/Images/sLocal-3.png",
        "price": 590,
        "quantity": 0,
    },
    {
        "id": 40,
        "title": "Vegetable Pizza",
        "description": "Vegetables, Pizza Sauce And Cheese",
        "thumbnail": "/Images/sLocal-4.png",
        "price": 590,
        "quantity": 0,
    },
    {
        "id": 50,
        "title": "Hot n Spicy",
        "description": "Hot and Spicy Chicken Onion, Jalapeno",
        "thumbnail": "/Images/sLocal-5.png",
        "price": 590,
        "quantity": 0,
    },
    {
        "id": 60,
        "title": "Chicken Tandoori",
        "description": "Our Traditionally Developed Tandoori Chicken with Onion, Olives, Jalapeno and Tomato Sauce",
        "thumbnail": "/Images/sLocal-6.png",
        "price": 590,
        "quantity": 0,
    },
]